#benchmark_classes:
#- XSBench:
#  - XSBench_CUDA
#  - XSBench_OpenMP_Offload
benchmarks:
- XSBench_OpenMP_threading:
  - "/home/mseryn/XSBench/openmp-threading/XSBench -m event"
#- RSBench_OpenMP_threading:
#  - "/home/mseryn/RSBench/openmp-threading/rsbench -m event"
debug: true
formatter_modes:
- PandasPickle
- CSV
iterations: 1
log: true
memory_modes:
- high_watermark
- memory_over_time
nvidia_modes:
- api_trace
- gpu_trace
- power_over_time
perf_counters:
- Instructions
- cpu-cycles
- LLC-stores
- page-faults
- major-faults
pmu_count: 4
test_name: DEFAULTNAME
time_count: 1000
