benchmark_configurations:
- XSBench:
    kwarg1: thingy
    kwarg2: otherThingy
- RSBench:
    kwarg1: things
benchmarks:
- XSBench
- RSBench
debug: true
formatter_modes:
- CSV
iterations: 2
log: true
memory_modes:
- high_watermark
- memory_over_time
nvidia_modes:
- api_trace
- gpu_trace
- power_over_time
perf_counters:
- Instructions
- cpu-cycles
- LLC-stores
- page-faults
- major-faults
- DRAM_BW_Use
- Average_Frequency
- CPU_Utilization
pmu_count: 4
test_name: DEFAULT
time_count: 100
