benchmarks:
  TestBench:
    runner: "TestBench"
    waittimes:
      - 1
      - 4
      - 8

collection_modes:
  perf:
    pmu_count: 4
  memory:
#    modes:
#      - high_watermark
#      - memory_over_time
#  nvidia:
#    modes:
#      - api_trace
#      - gpu_trace
#      - power_over_time
#      - power_summary
#    gen: sm_80

formatter_modes:
- PandasPickle
- CSV

perf_counters:
- Instructions
- cpu-cycles
- LLC-stores
- page-faults
- major-faults

iterations: 1
time_count: 1000
log: true
test_name: TESTNAME
