benchmarks:
  TestBench:
    runner: "TestBench"
    waittimes:
      - 1

collection_modes:
  perf:
    pmu_count: 4
  nvidia:
    modes:
      - power_summary
    gen:
      - sm_80
#  memory:
#    modes:
#      - high_watermark
#      - memory_over_time
#      - api_trace
#      - gpu_trace
#      - power_over_time
#    gen: sm_80

formatter_modes:
- PandasPickle
- CSV

perf_counters:
- instructions
- cache-misses

iterations: 1
time_count: 1000
log: true
test_name: nvidiapoweroverTime
