#benchmark_classes:
#- XSBench:
#  - XSBench_CUDA
#  - XSBench_OpenMP_Offload
benchmarks:
  xsbench_openmp_threading:
    runner: "generic_benchmark"
    name: "XSBench_OpenMP_threading"
    cmd: "/home/mseryn/XSBench/openmp-threading/XSBench -m event"
  xsbench_openmp_offload:
    runner: "XSBenchOpenmpOffload"
    loc: "/home/mseryn/XSBench/openmp-offload/"

collection_modes:
  perf:
    pmu_count: 4
  memory:
    modes:
      - high_watermark
      - memory_over_time
  nvidia:
    modes:
      - api_trace
      - gpu_trace
      - power_over_time
    gen: sm_80

formatter_modes:
- PandasPickle
- CSV

perf_counters:
- Instructions
- cpu-cycles
- LLC-stores
- page-faults
- major-faults

iterations: 1
time_count: 1000
log: true
test_name: DEFAULTNAME
